config/routes.rb
Rails.application.routes.draw do
  resources :compras
  resources :responsavels

end

app/models/compra.rb
class Compra < ActiveRecord::Base
  belongs_to :responsavel

  validates_presence_of :description

end

app/models/responsavel.rb
class Responsavel < ActiveRecord::Base

  validates_presence_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  before_action :set_compra, only: [:show, :edit, :update, :destroy]
  before_action :set_responsaveis

  # GET /compras
  # GET /compras.json
  def index
    @compras = Compra.all
  end

  # GET /compras/1
  # GET /compras/1.json
  def show
  end

  # GET /compras/new
  def new
    @compra = Compra.new
  end

  # GET /compras/1/edit
  def edit
  end

  # POST /compras
  # POST /compras.json
  def create
    @compra = Compra.new(compra_params)

    respond_to do |format|
      if @compra.save
        format.html { redirect_to @compra, notice: 'Compra was successfully created.' }
        format.json { render :show, status: :created, location: @compra }
      else
        format.html { render :new }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compras/1
  # PATCH/PUT /compras/1.json
  def update
    respond_to do |format|
      if @compra.update(compra_params)
        format.html { redirect_to @compra, notice: 'Compra was successfully updated.' }
        format.json { render :show, status: :ok, location: @compra }
      else
        format.html { render :edit }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compras/1
  # DELETE /compras/1.json
  def destroy
    @compra.destroy
    respond_to do |format|
      format.html { redirect_to compras_url, notice: 'Compra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra
      @compra = Compra.find(params[:id])
    end

    def set_responsaveis
      @responsavel = Responsavel.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compra_params
      params.require(:compra).permit(:data, :description, :comprado, :responsavel_id)
    end
end

app/controllers/responsavels_controller.rb
class ResponsavelsController < ApplicationController
  before_action :set_responsavel, only: [:show, :edit, :update, :destroy]

  # GET /responsavels
  # GET /responsavels.json
  def index
    @responsavels = Responsavel.all
  end

  # GET /responsavels/1
  # GET /responsavels/1.json
  def show
  end

  # GET /responsavels/new
  def new
    @responsavel = Responsavel.new
  end

  # GET /responsavels/1/edit
  def edit
  end

  # POST /responsavels
  # POST /responsavels.json
  def create
    @responsavel = Responsavel.new(responsavel_params)

    respond_to do |format|
      if @responsavel.save
        format.html { redirect_to @responsavel, notice: 'Responsavel was successfully created.' }
        format.json { render :show, status: :created, location: @responsavel }
      else
        format.html { render :new }
        format.json { render json: @responsavel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responsavels/1
  # PATCH/PUT /responsavels/1.json
  def update
    respond_to do |format|
      if @responsavel.update(responsavel_params)
        format.html { redirect_to @responsavel, notice: 'Responsavel was successfully updated.' }
        format.json { render :show, status: :ok, location: @responsavel }
      else
        format.html { render :edit }
        format.json { render json: @responsavel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responsavels/1
  # DELETE /responsavels/1.json
  def destroy
    @responsavel.destroy
    respond_to do |format|
      format.html { redirect_to responsavels_url, notice: 'Responsavel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_responsavel
      @responsavel = Responsavel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def responsavel_params
      params.require(:responsavel).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/responsavels_helper.rb
module ResponsavelsHelper
end

app/views/compras/_form.html.erb
<%= form_for(@compra) do |f| %>
  <% if @compra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@compra.errors.count, "error") %> prohibited this compra from being saved:</h2>

      <ul>
      <% @compra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :comprado %><br>
    <%= f.check_box :comprado %>
  </div>
  <div class="field">
    <%= f.label :responsavel_id %><br>
    <%= f.collection_select :responsavel_id, @responsavel, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/compras/edit.html.erb
<h1>Editing Compra</h1>

<%= render 'form' %>

<%= link_to 'Show', @compra %> |
<%= link_to 'Back', compras_path %>

app/views/compras/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Listing Compras</h3>

<table class="table">
  <thead>
    <tr>
      <th>Data</th>
      <th>Descrição</th>
      <th>Comprado</th>
      <th>Responsavel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @compras.each do |compra| %>
      <tr>
        <td><%= compra.data %></td>
        <td><%= compra.description %></td>
        <td><%= compra.comprado %></td>
        <td><%= compra.responsavel.name %></td>
        <td><%= link_to 'Show', compra, class:'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_compra_path(compra), class:'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', compra, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-primary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Compra', new_compra_path %>

app/views/compras/new.html.erb
<h1>New Compra</h1>

<%= render 'form' %>

<%= link_to 'Back', compras_path %>

app/views/compras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @compra.data %>
</p>

<p>
  <strong>Description:</strong>
  <%= @compra.description %>
</p>

<p>
  <strong>Comprado:</strong>
  <%= @compra.comprado %>
</p>

<p>
  <strong>Responsavel:</strong>
  <%= @compra.responsavel.name %>
</p>

<%= link_to 'Edit', edit_compra_path(@compra) %> |
<%= link_to 'Back', compras_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lista de Compras</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Lista de Compras</a>
    <div class="collapse navbar-collapse">
      <div class="navbar-nav">
        <%= link_to 'Responsáveis', responsavels_path, class: 'nav-item nav-link' %>
        <%= link_to 'Compras', compras_path, class: 'nav-item nav-link' %>

      </div>
    </div>
  </nav>

  <main class="container" role="main">
    <%= yield %>
  </main>

</body>
</html>

app/views/responsavels/_form.html.erb
    <%= form_for(@responsavel) do |f| %>
      <% if @responsavel.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@responsavel.errors.count, "error") %> prohibited this responsavel from being saved:</h2>

          <ul>
          <% @responsavel.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>

app/views/responsavels/edit.html.erb
<h1>Editing Responsavel</h1>

<%= render 'form' %>

<%= link_to 'Show', @responsavel %> |
<%= link_to 'Back', responsavels_path %>

app/views/responsavels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Responsavels</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responsavels.each do |responsavel| %>
      <tr>
        <td><%= responsavel.name %></td>
        <td><%= link_to 'Show', responsavel, class:'btn btn-primary'  %></td>
        <td><%= link_to 'Edit', edit_responsavel_path(responsavel), class:'btn btn-primary'  %></td>
        <td><%= link_to 'Destroy', responsavel, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-primary'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Responsavel', new_responsavel_path %>

app/views/responsavels/new.html.erb
<h1>New Responsavel</h1>

<%= render 'form' %>

<%= link_to 'Back', responsavels_path %>

app/views/responsavels/show.html.erb
<p id="notice"><%= notice %></p>

<form>
  <div class="form-group">

      <p>
        <strong>Name:</strong>
        <%= @responsavel.name %>
      </p>

      <%= link_to 'Edit', edit_responsavel_path(@responsavel) %> |
      <%= link_to 'Back', responsavels_path %>
    </div>
  </form>